# Generated by Django 5.2.8 on 2025-11-26 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tên mùa giải')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=False, verbose_name='Đang diễn ra')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên cầu thủ')),
                ('position', models.CharField(choices=[('Goalkeeper', 'Thủ môn'), ('Defender', 'Hậu vệ'), ('Midfielder', 'Tiền vệ'), ('Forward', 'Tiền đạo')], max_length=20, verbose_name='Vị trí')),
                ('nationality', models.CharField(default='Việt Nam', max_length=50, verbose_name='Quốc tịch')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('jersey_number', models.IntegerField(blank=True, null=True, verbose_name='Số áo')),
                ('status', models.CharField(choices=[('Active', 'Đang thi đấu'), ('Injured', 'Chấn thương'), ('Suspended', 'Treo giò'), ('Free Agent', 'Cầu thủ tự do')], default='Active', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='quanly.team', verbose_name='Đội bóng')),
            ],
        ),
    ]
