# Generated by Django 5.2.8 on 2025-11-26 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_season_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_score', models.IntegerField(default=0, verbose_name='Bàn thắng đội nhà')),
                ('away_score', models.IntegerField(default=0, verbose_name='Bàn thắng đội khách')),
                ('match_date', models.DateTimeField(verbose_name='Ngày giờ đá')),
                ('round_number', models.IntegerField(verbose_name='Vòng đấu')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Sắp đá'), ('FINISHED', 'Đã kết thúc')], default='SCHEDULED', max_length=20, verbose_name='Trạng thái')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='quanly.team', verbose_name='Đội khách')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='quanly.team', verbose_name='Đội nhà')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.season', verbose_name='Mùa giải')),
            ],
        ),
    ]
