# Generated by Django 5.2.8 on 2025-11-26 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('end_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('salary', models.BigIntegerField(verbose_name='Lương (VND)')),
                ('contract_type', models.CharField(choices=[('Permanent', 'Hợp đồng dài hạn'), ('Loan', 'Cho mượn')], default='Permanent', max_length=20, verbose_name='Loại hợp đồng')),
                ('clauses', models.TextField(blank=True, null=True, verbose_name='Điều khoản chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.player', verbose_name='Cầu thủ')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.team', verbose_name='Đội bóng')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_fee', models.BigIntegerField(verbose_name='Phí chuyển nhượng (VND)')),
                ('status', models.CharField(choices=[('pending_approval', 'Chờ phê duyệt'), ('approved', 'Đã chấp thuận'), ('rejected', 'Bị từ chối'), ('negotiating', 'Đang thương lượng')], default='pending_approval', max_length=20, verbose_name='Trạng thái')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='quanly.team', verbose_name='Đội bán')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.player', verbose_name='Cầu thủ')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='quanly.team', verbose_name='Đội mua')),
            ],
        ),
    ]
