# Generated by Django 5.2.8 on 2025-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0005_feedback_playerstat_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã cài đặt')),
                ('value', models.CharField(max_length=255, verbose_name='Giá trị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
    ]
