# Generated by Django 5.2.8 on 2025-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0008_match_event_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
