# Generated by Django 5.2.8 on 2025-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, help_text='Đơn vị: cm', null=True, verbose_name='Chiều cao'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Đơn vị: kg', null=True, verbose_name='Cân nặng'),
        ),
    ]
