# Generated by Django 5.2.8 on 2025-12-22 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0012_prediction_confidence_score_prediction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_rest_days', models.IntegerField(default=5, help_text='Khoảng cách tối thiểu giữa 2 trận của cùng đội', verbose_name='Số ngày nghỉ tối thiểu')),
                ('max_rest_days', models.IntegerField(default=7, help_text='Khoảng cách tối đa (soft constraint)', verbose_name='Số ngày nghỉ tối đa')),
                ('valid_time_slots', models.JSONField(default=list, help_text='Ví dụ: [{"h": 17, "m": 0}, {"h": 19, "m": 15}]', verbose_name='Khung giờ hợp lệ')),
                ('max_consecutive_away', models.IntegerField(default=3, verbose_name='Số trận sân khách liên tiếp tối đa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='quanly.season', verbose_name='Mùa giải')),
            ],
            options={
                'verbose_name': 'Cấu hình lịch thi đấu',
                'verbose_name_plural': 'Cấu hình lịch thi đấu',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('GENERATE', 'Tạo lịch'), ('APPROVE', 'Duyệt lịch'), ('REJECT', 'Từ chối lịch'), ('MODIFY', 'Chỉnh sửa'), ('DELETE', 'Xóa lịch')], max_length=20, verbose_name='Hành động')),
                ('details', models.JSONField(default=dict, help_text='Thông tin chi tiết về hành động', verbose_name='Chi tiết')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_logs', to='quanly.season', verbose_name='Mùa giải')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký tạo lịch',
                'verbose_name_plural': 'Nhật ký tạo lịch',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_matches', models.JSONField(help_text='Danh sách các trận đấu dạng JSON', verbose_name='Lịch thi đấu đề xuất')),
                ('feasibility_score', models.FloatField(help_text='Từ 0-100', verbose_name='Điểm khả thi')),
                ('constraint_violations', models.JSONField(default=list, help_text='Các ràng buộc bị vi phạm (nếu có)', verbose_name='Danh sách vi phạm ràng buộc')),
                ('statistics', models.JSONField(default=dict, help_text='Số trận, số vòng, cân bằng sân nhà/khách, v.v.', verbose_name='Thống kê lịch thi đấu')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Bị từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_proposals', to='quanly.season', verbose_name='Mùa giải')),
            ],
            options={
                'verbose_name': 'Đề xuất lịch thi đấu',
                'verbose_name_plural': 'Đề xuất lịch thi đấu',
                'ordering': ['-created_at'],
            },
        ),
    ]
