# Generated by Django 5.2.8 on 2025-12-24 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0013_scheduleconfiguration_schedulegenerationlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulegenerationlog',
            name='season',
        ),
        migrations.RemoveField(
            model_name='schedulegenerationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduleproposal',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='scheduleproposal',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='scheduleproposal',
            name='season',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tin nhắn Chatbot',
                'verbose_name_plural': 'Tin nhắn Chatbot',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ScheduleConfiguration',
        ),
        migrations.DeleteModel(
            name='ScheduleGenerationLog',
        ),
        migrations.DeleteModel(
            name='ScheduleProposal',
        ),
    ]
