# Generated by Django 5.2.8 on 2025-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0014_remove_schedulegenerationlog_season_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Lịch sử Chat AI', 'verbose_name_plural': 'Lịch sử Chat AI'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='Tin nhắn người dùng'),
        ),
    ]
