# Generated by Django 5.2.8 on 2025-12-26 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0028_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContractTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Đang xử lý'), ('Completed', 'Hoàn thành'), ('Failed', 'Thất bại')], default='Pending', max_length=20, verbose_name='Trạng thái')),
                ('result_json', models.TextField(blank=True, null=True, verbose_name='Kết quả JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
    ]
