# Generated by Django 5.2.8 on 2025-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0029_aicontracttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.IntegerField(default=0, verbose_name='Điểm thưởng'),
        ),
        migrations.DeleteModel(
            name='AIContractTask',
        ),
    ]
