# Generated by Django 5.2.8 on 2025-12-26 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0030_user_reward_points_delete_aicontracttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=100000, verbose_name='Giá vé')),
                ('discount', models.IntegerField(default=0, verbose_name='Giảm giá (Điểm)')),
                ('final_amount', models.IntegerField(verbose_name='Thực trả')),
                ('payment_method', models.CharField(default='bank', max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(default='paid', max_length=20, verbose_name='Trạng thái')),
                ('ticket_code', models.CharField(max_length=20, unique=True, verbose_name='Mã vé')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tickets/qr/', verbose_name='Mã QR')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mua')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.match', verbose_name='Trận đấu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
            ],
        ),
    ]
