# Generated by Django 5.2.8 on 2025-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0031_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
