# Generated by Django 5.2.8 on 2026-01-01 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0032_transferrequest_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='notes',
        ),
        migrations.CreateModel(
            name='TransferMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quanly.transferrequest', verbose_name='Thương vụ')),
            ],
            options={
                'verbose_name': 'Tin nhắn đàm phán',
                'verbose_name_plural': 'Tin nhắn đàm phán',
                'ordering': ['created_at'],
            },
        ),
    ]
